services:
  - type: web
    name: village-portal
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT "app:create_app()"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
